vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        vehicles:
            uri_prefix: /images/vehicles
            upload_destination: '%kernel.project_dir%/assets/images/vehicles'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true

        service_image:
            uri_prefix: /images/services
            upload_destination: '%kernel.project_dir%/assert/images/services'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
