vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        vehicles:
            uri_prefix: /images/vehicles
            upload_destination: '%kernel.project_dir%/public/images/vehicles'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true

        service_image:
            uri_prefix: /images/services
            upload_destination: '%kernel.project_dir%/public/images/services'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true

        vehicle_images:
            uri_prefix: /images/vehicle_images
            upload_destination: '%kernel.project_dir%/public/images/vehicle_images'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
