<?php

namespace App\Controller\Admin;

use App\Entity\Service;
use EasyCorp\Bundle\EasyAdminBundle\Config\Crud;
use EasyCorp\Bundle\EasyAdminBundle\Controller\AbstractCrudController;
use EasyCorp\Bundle\EasyAdminBundle\Field\ArrayField;
use EasyCorp\Bundle\EasyAdminBundle\Field\AssociationField;
use EasyCorp\Bundle\EasyAdminBundle\Field\CollectionField;
use EasyCorp\Bundle\EasyAdminBundle\Field\IdField;
use EasyCorp\Bundle\EasyAdminBundle\Field\ImageField;
use EasyCorp\Bundle\EasyAdminBundle\Field\NumberField;
use EasyCorp\Bundle\EasyAdminBundle\Field\TextareaField;
use EasyCorp\Bundle\EasyAdminBundle\Field\TextEditorField;
use EasyCorp\Bundle\EasyAdminBundle\Field\TextField;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Vich\UploaderBundle\Form\Type\VichImageType;

class ServiceCrudController extends AbstractCrudController
{
    public static function getEntityFqcn(): string
    {
        return Service::class;
    }

    public function configureFields(string $pageName): iterable
    {
        $vichMappingParams = $this->getParameter('vich_uploader.mappings');
//        dd($vichMappingParams);
        $vehicleImagePath = $vichMappingParams['service_image']['uri_prefix'];

//        yield from parent::configureFields(($pageName));
        yield NumberField::new('id')
            ->hideOnForm();
        yield TextField::new('label', 'Appellation');
        yield TextField::new('type');
        yield TextareaField::new('description');

        yield TextareaField::new('imageFile', 'Fichier de l\'image')
            ->setFormType(VichImageType::class)
            ->hideOnIndex();

        yield ImageField::new('imageName', 'Photo')->setBasePath($vehicleImagePath)->hideOnForm();
//        yield ImageField::new('imageName', 'Photo')->setBasePath('./images/services')->hideOnForm();
        yield AssociationField::new('garages');
    }

    public function configureCrud(Crud $crud): Crud
    {
//        return parent::configureCrud($crud); // TODO: Change the autogenerated stub
        return $crud
            ->setEntityLabelInPlural('Services')
            ->setEntityLabelInSingular('Service')
            ->setPageTitle('new', 'Ajouter un service')
            ->setPageTitle('edit', 'Modifier');
    }
}
